### PR TITLE
Fix last CS error

### PR DESCRIPTION
**Pull request by szepeviktor**
@darrenjacoby

### CODE REVIEW

**Comment by darrenjacoby** [comment]
@szepeviktor Thanks, I am close to releasing 2.0.0 which has been mostly re-written. I should have a beta up soon, and then perhaps you can check for CS errors again? 🥴

**Comment by szepeviktor** [comment]
Okay.

**Comment by darrenjacoby** [comment]
Merging this so long, thank you for contributing, I appreciate it!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
