### PR TITLE
Introduce phpstan and fix most errors

### PR DESCRIPTION
**Pull request by szepeviktor**
- add phpstan
- fix errors
- introduce a helper class used only in static analysis
- remove execution bit from src/Module/RemoveWidgets.php
- very few errors left, please help me

### CODE REVIEW

**Comment by szepeviktor** [comment]
Remaining errors I am not able to understand.

```
 ------ ----------------------------------------------------------------------------------------------------------------
  Line   Instance.php
 ------ ----------------------------------------------------------------------------------------------------------------
  55     Parameter #2 $haystack of function in_array expects array, array|string given.
  58     Parameter #2 $haystack of function in_array expects array, array|string given.
  62     Method Sober\Intervention\Instance::aliasUserRoles() should return array|string but returns array|string|null.
  94     Method Sober\Intervention\Instance::aliasTaxTag() should return array|string but returns array|string|null.
 ------ ----------------------------------------------------------------------------------------------------------------

 ------ -----------------------------------------------------------------------------------------------------------------------------
  Line   Labels.php (in context of class Sober\Intervention\Module\UpdateLabelPage)
 ------ -----------------------------------------------------------------------------------------------------------------------------
  19     Cannot access property $labels on WP_Post_Type|null.
  21     Parameter #2 $arr of method Sober\Intervention\Module\UpdateLabelPage::isArrayValueSet() expects array, array|string given.
  24     Parameter #2 $arr of method Sober\Intervention\Module\UpdateLabelPage::isArrayValueSet() expects array, array|string given.
 ------ -----------------------------------------------------------------------------------------------------------------------------

 ------ -----------------------------------------------------------------------------------------------------------------------------
  Line   Labels.php (in context of class Sober\Intervention\Module\UpdateLabelPost)
 ------ -----------------------------------------------------------------------------------------------------------------------------
  19     Cannot access property $labels on WP_Post_Type|null.
  21     Parameter #2 $arr of method Sober\Intervention\Module\UpdateLabelPost::isArrayValueSet() expects array, array|string given.
  24     Parameter #2 $arr of method Sober\Intervention\Module\UpdateLabelPost::isArrayValueSet() expects array, array|string given.
 ------ -----------------------------------------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------------------------------
  Line   Module/UpdateDashboardColumns.php
 ------ ---------------------------------------------------------------------------------------------------------------
  32     Parameter #1 $args of method Sober\Intervention\Instance::setDefaultConfig() expects array|string, int given.
 ------ ---------------------------------------------------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------------------------------------
  Line   Module/UpdatePagination.php
 ------ ---------------------------------------------------------------------------------------------------------------
  35     Parameter #1 $args of method Sober\Intervention\Instance::setDefaultConfig() expects array|string, int given.
 ------ ---------------------------------------------------------------------------------------------------------------
```

**Comment by darrenjacoby** [comment]
@szepeviktor thanks for this, I'm going to take a look at the above this week.

**Comment by szepeviktor** [comment]
You're welcome.
Please keep in mind that a year has passed since this PR was written.

**Comment by darrenjacoby** [comment]
Sure, I will be sure to update tools and re-test. Planning this as part of a bigger release.

**Comment by szepeviktor** [comment]
```json

  "require-dev": {
    "php": "~7.1",
    "squizlabs/php_codesniffer": "2.*",
    "szepeviktor/phpstan-wordpress": "^0.6.1"
  },
```

**Comment by darrenjacoby** [comment]
I actually updated php_codesniffer to 3.5.0 yesterday and cleared out all the errors, https://github.com/soberwp/intervention/blob/master/composer.json#L26

I am ignoring `Generic.Files.LineLength` and `PSR1.Files.SideEffects`, https://github.com/soberwp/intervention/blob/master/phpcs.xml

I'll take a look at phpstan-wordpress and resolve any errors there.

**Comment by szepeviktor** [comment]
Okay.

`PSR1.Files.SideEffects` is an inherently bad wordpressy practice.
Please reconsider it.
Maybe it is enough to ignore it in 1 file.

```php
<?php // phpcs:disable PSR1.Files.SideEffects
```

**Comment by darrenjacoby** [comment]
Will do, I'll remove and see what errors come up and if there's an option to remove entirely.

**Pull request closed without merging**
